name: ccb_app_visitas
description: "Aplicativo para controle de visitas à enfermos e demais irmãos da CCB. Criado voluntariamente e sem custos."
publish_to: 'Genesis Dev Studio' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash_logo.png
  
